title: Путеводитель по переезду в Армению
author: HayWiki Team
email: druidvav+haywiki@gmail.com
description: >-
  Полезная информация о переезде, жизни и легализации в Армении.
baseurl: ""
url: "https://haywiki.org"
github_username: haywiki
lang: ru

markdown: kramdown
theme: minima
plugins:
  - jekyll-remote-theme
#  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-relative-links
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - robots.txt
sass:
  sass_dir: _sass
relative_links:
  enabled:     true
  collections: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      display_toc: true

# Content variables

mir_cards_date: "23.10.2022"
