title: Путеводитель по Армении для эмигранта
#email: druidvav@gmail.com
#description: >-
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://haywiki.github.io"
github_username: haywiki

markdown: kramdown
theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - robots.txt

header_pages:
